---
- name: OSPF
  hosts: routers
  gather_facts: false
  connection: local

  vars:
    cli:
      username: carter
      password: cisco
  
  tasks:
    - name: enable OSPF
      ios_config:
        authorize: yes
        provider: "{{ cli }}"
        parents: router ospf 1
        lines:
          - network 0.0.0.0 255.255.255.255 area 0
      
      register: print_output

    - debug: var=print_output
