---
- name: Add access-list
  hosts: switches
  gather_facts: false
  connection: local

  vars: 
    cli: 
      username: carter
      password: cisco
  
  tasks: 
    - name: Create VLANs
      ios_config: 
        authorize: yes
        provider: "{{ cli }}"
        lines:
          - vlan 10
